/*-----------------------------------------------------------------------------
 * @file     | OEM_PORT686C.H
 * ----------+-----------------------------------------------------------------
 * @function | OEM_PORT686C.C Function prototype include definition
 * ----------+-----------------------------------------------------------------
 * @model    | Notebook Computer Embedded Controller Firmware
 * @version  | Kernel-14.4, OEM-M.Style Reference Code-1.0
 * @author   | OEM
 * @note     | Copyright(c)2010-2013, ITE Tech. Inc. All rights reserved.
 *---------------------------------------------------------------------------*/
#ifndef OEM_PM4_H
#define OEM_PM4_H



//-----------------------------------------------------------------------------
#endif  //OEM_PM4_H
/*-----------------------------------------------------------------------------
 * End of OEM_PM4.H */